```{r, include=FALSE}
library(latex)
library(enotation)
library(emargintag)
library(webshot)
#library(linguisticsdown)
library(formatR)
```


```{r, label = 'setup', include=FALSE}
#knit
knitr::opts_chunk$set(
    echo = TRUE, 
    fig.retina = 2, 
    fig.align = "center",
    out.width="100%",
    message=FALSE,
    warning=FALSE,
    error=FALSE,
    results = 'hold',
    # Truncar líneas en PDF
    tidy = "styler"
    # https://bookdown.org/yihui/rmarkdown-cookbook/opts-tidy.html
    #tidy=TRUE, 
    #tidy.opts=list(width.cutoff=60)
)

if(knitr::is_html_output()){
    knitr::opts_chunk$set(comment = '')    
}
if(knitr::is_latex_output()){
    knitr::opts_chunk$set(comment = '##')    
}

# -shell-escape
# https://stackoverflow.com/questions/55459948/latex-shell-escape-options-in-yaml-header-dont-use?noredirect=1#comment97651281_55459948
options(tinytex.engine_args = '-halt-on-error -interaction=nonstopmode -shell-escape') 

## numbers >= 10^5 will be denoted in scientific notation,
## and rounded to 3 digits
options(scipen = 0, digits = 7)

# usar versión más reciente de pandoc
rmarkdown::find_pandoc()
```

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(
    c(
        .packages(), 
        'bookdown', 
        'knitr', 
        'rmarkdown'
    ), 
    'packages.bib'
)
```


```{r, echo=FALSE}
# trick to be able to customize default output (see pre.custom-output in style.css)
# https://stackoverflow.com/questions/65495605/in-r-bookdown-how-do-i-set-the-default-code-output-background-color
knitr::opts_chunk$set(class.output = 'egitbook-output')
```

